# -*- coding: utf-8 -*-
"""daily_life_copilot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rDbmmCFrYr6aqKdWhuRAVa0m4fQDeHlz
"""

import datetime

def generate_study_plan(start_date, exam_days=30):
    subjects = ["Math", "Python", "Data Structures"]

    print(f"{'Day':<5} | {'Date':<12} | {'Phase':<12} | {'Study Focus'}")
    print("-" * 60)

    for day in range(1, exam_days + 1):
        current_date = start_date + datetime.timedelta(days=day-1)

        # Define Phase logic
        if day <= 10:
            phase = "Foundations"
            task = "Theory & Basic Exercises"
        elif day <= 25:
            phase = "Application"
            task = "Solving Problems & Coding DSA"
        else:
            phase = "Final Review"
            task = "Past Papers & Mock Exams"

        # Format the output
        date_str = current_date.strftime("%b %d")
        print(f"{day:<5} | {date_str:<12} | {phase:<12} | {', '.join(subjects)}: {task}")

# Run the generator starting today
generate_study_plan(datetime.date.today())